version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      server:
        condition: service_healthy

