# Use the official Rust image as a parent image
FROM rust:latest

# Set the working directory
WORKDIR /usr/src/myapp

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

RUN apt update

RUN apt install -y protobuf-compiler

# Build the application
RUN cargo build --release

# Command to run the client
CMD ["./target/release/client"]
