# Use the official Rust image as a parent image
FROM rust:latest

# Set the working directory
WORKDIR /usr/src/myapp

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

RUN apt update

RUN apt install -y protobuf-compiler

# Build the application
RUN cargo build --release

# Expose the port the server listens on
EXPOSE 50051

# Command to run the server
CMD ["./target/release/server"]
